name: Android CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.10.2
    - name: Check CMake Version
      run: cmake --version
    - name: set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 18
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Checkout glog-action repository
      uses: actions/checkout@v4
      with:
        repository: glogai/glog-action
        token: ${{ secrets.PAT_TOKEN }}
        path: .github/glog-action
        ref: main

    - name: Run Glog.AI from private repo
      uses: ./.github/glog-action
      with:
        lang: 'java'
        debug: 'false'
        upload: 'true'
        github-token: ${{ secrets.PAT_TOKEN }}
        glog-token: ${{ secrets.GLOG_TOKEN }}
